name: Quick Check

on:
  workflow_dispatch:

concurrency:
  group: bogram-ios-quick-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quick-check:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: '0'

      - name: Restore Bazel cache
        uses: actions/cache@v4
        with:
          path: ~/telegram-bazel-cache
          key: ${{ runner.os }}-telegram-bazel-${{ hashFiles('versions.json', 'build-system/**', '**/*.bzl', '**/BUILD', '**/BUILD.bazel', '.gitmodules') }}
          restore-keys: |
            ${{ runner.os }}-telegram-bazel-

      - name: Set active Xcode path
        run: |
          XCODE_VERSION=$(cat versions.json | python3 -c 'import json,sys;obj=json.load(sys.stdin);print(obj["xcode"]);')
          sudo xcode-select -s /Applications/Xcode_$XCODE_VERSION.app/Contents/Developer

      - name: Create canonical source directory
        run: |
          set -x
          sudo mkdir -p /Users/Shared
          rm -rf /Users/Shared/telegram-ios
          cp -R $GITHUB_WORKSPACE /Users/Shared/
          mv /Users/Shared/$(basename $GITHUB_WORKSPACE) /Users/Shared/telegram-ios

      - name: Compile Check
        run: |
          set -x

          SOURCE_DIR=/Users/Shared/telegram-ios
          BAZEL_USER_ROOT="/private/var/tmp/_bazel_containerhost"

          cd $SOURCE_DIR

          python3 build-system/Make/ImportCertificates.py --path build-system/fake-codesigning/certs
          python3 -u build-system/Make/Make.py \
            --bazelUserRoot="$BAZEL_USER_ROOT" \
            --cacheDir="$HOME/telegram-bazel-cache" \
            build \
            --configurationPath="build-system/bogram-unsigned-configuration.json" \
            --codesigningInformationPath=build-system/fake-codesigning \
            --configuration=debug_sim_arm64 \
            --buildNumber=10000
